version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/{{cookiecutter.project_slug}}

    steps:
      - checkout
      - restore_cache:
          keys:
            {% raw %}
            - v1-dependencies-{{ checksum "package.json" }}
            {% endraw %}
            - v1-dependencies-
      - run:
          name: Install Project Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          {% raw %}
          key: v1-dependencies-{{ checksum "package.json" }}
          {% endraw %}
      - run:
          name: Run Tests
          command: npm run test:coverage
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
